### ISSUE TITLE
no cache found

### ISSUE THREAD

**Issue by openbeast90** [alexjdesio/Skyblock-Auctions-Analyzer-Discord-Bot#10]
when i do node bot.js it says base items loaded no ache found then it closes

**Comment by alexjdesio** [comment]
The bot will run without a cache and will automatically create a cache.json file when you successfully run !watch for the first time. Please download a fresh copy of the code from github and let me know if this issue persists. For frequently asked questions, take a look at the [getting started guide](https://github.com/alexjdesio/Skyblock-Auctions-Analyzer-Discord-Bot#getting-started)and feel free to post additional questions/comments in the issue queue.
