### ISSUE TITLE
Why it says invalid token, i know its right one

### ISSUE THREAD

**Issue by Andrelissss** [alexjdesio/Skyblock-Auctions-Analyzer-Discord-Bot#13]
Base items successfully loaded.
No cache found.
(node:7468) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (C:\Users\Admin\Desktop\botas\node_modules\discord.js\src\client\Client.js:206:52)
    at Object.<anonymous> (C:\Users\Admin\Desktop\botas\bot.js:38:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7468) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7468) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Andrelissss** [comment]
so this is messed up i ran it anyway
![image](https://user-images.githubusercontent.com/80877847/112108875-7ac6ed80-8bb9-11eb-84e0-58ed7c16680a.png)

**Comment by alexjdesio** [comment]
I'd love to fix what is messed up! Can you describe what part of the necessary files section needs to be changed?

Thanks for your help!

**Comment by Andrelissss** [comment]
In auth.json there should be discord token and in key.json hypixel api key.
![image](https://user-images.githubusercontent.com/80877847/112315660-007a9400-8cb3-11eb-9fbd-312e5f383a22.png)
this part is messed up

**Comment by alexjdesio** [comment]
This has been fixed, thank you for your feedback!
