### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by Andrelissss** [alexjdesio/Skyblock-Auctions-Analyzer-Discord-Bot#6]
can you write me in discord? or seld your server link.
idkkkk#1492

**Comment by zemlyak** [comment]
do "npm i" and create 2 files in the bot directory

"auth.json" with the following content
`{
        "token" : "insert your discord bot token here"
}`
and "key.json" with this
`{
       "api_key" : "your hypixel api key"
}`

then do "node bot.js"

**Comment by alexjdesio** [comment]
> 
> 
> can you write me in discord? or sent your server link.
> idkkkk#1492

Thank you for your message! I just posted a full write up detailing [how to get started](https://github.com/alexjdesio/Skyblock-Auctions-Analyzer-Discord-Bot#getting-started). Please take a look and let me know if you have any further questions.
