### ISSUE TITLE
do "npm i" and create 2 files in the bot directory

### ISSUE THREAD

**Issue by kittynator1** [alexjdesio/Skyblock-Auctions-Analyzer-Discord-Bot#8]
do "npm i" and create 2 files in the bot directory

"auth.json" with the following content
`{
        "token" : "insert your discord bot token here"
}`
and "key.json" with this
`{
       "api_key" : "your hypixel api key"
}`

then do "node bot.js"

_Originally posted by @zemlyak in https://github.com/alexjdesio/Skyblock-Auctions-Analyzer-Discord-Bot/issues/6#issuecomment-803267913_

After doing this, when i run the bot, it say:

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'discord.io'

**Comment by alexjdesio** [comment]
Please download the most recent version of the bot from the main branch and let me know if this issue persists. In addition, I updated the README today to include a guide on [getting started](https://github.com/alexjdesio/Skyblock-Auctions-Analyzer-Discord-Bot#getting-started).
